### ISSUE TITLE
PermissionError: [WinError 5] Access is denied Error in Windows environment

### ISSUE THREAD

**Issue by sreek011** [mwilliamson/stickytape#14]
Hi, getting stuck with this problem with the following details:
Kindly guide.

Thanks in advance

Command:
stickytape C:\Users\xyz\Documents\xyz\PyProjects\myproj\mypscript.py --add-python-path C:\Users\xyz\anaconda3\ --python-binary C:\Users\xyz\anaconda3\Lib\site-packages --output-file C:\Users\xyz\Documents\xyz\PyProjects\myproj\mypscriptOne.py 

Additional information. 
- command invoked from directory ..  C:\Users\xyz\Documents\xyz\PyProjects\myproj\
- windows command shell in administrator mode
- Environment - Windows 10, anaconda 3, python 3.7

Output:
Traceback (most recent call last):
  File "c:\users\panicker\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\panicker\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\panicker\anaconda3\Scripts\stickytape.exe\__main__.py", line 7, in <module>
  File "c:\users\panicker\anaconda3\lib\site-packages\stickytape\main.py", line 10, in main
    args.script, args.add_python_path, args.python_binary)
  File "c:\users\panicker\anaconda3\lib\site-packages\stickytape\__init__.py", line 9, in script
    python_paths = [os.path.dirname(path)] + add_python_paths + _read_sys_path_from_python_bin(python_binary)
  File "c:\users\panicker\anaconda3\lib\site-packages\stickytape\__init__.py", line 24, in _read_sys_path_from_python_bin
    env={}
  File "c:\users\panicker\anaconda3\lib\subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "c:\users\panicker\anaconda3\lib\subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "c:\users\panicker\anaconda3\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "c:\users\panicker\anaconda3\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
PermissionError: [WinError 5] Access is denied

**Comment by mwilliamson** [comment]
The `--python-binary` argument needs to point to a Python binary/executable. It looks like you're pointing it towards a `site-packages` directory?

**Comment by sreek011** [comment]
Dear mWilliamson, Thanks a lot for your kind reply. It started working.
Sreekumar

**Comment by mwilliamson** [comment]
Glad you got it working.
